DynamoDB Streams
Home24/dynalite pull request #1
Opened 2016-12-12 16:18 UTC by kiril-pirozenko-home24

2016-12-13 12:52 UTC, mariusgrigaitis requested changes

2016-12-13 12:52 UTC, mariusgrigaitis commented on .vscode/launch.json
> +{
??? what's this mess?

2016-12-13 12:52 UTC, mariusgrigaitis commented on actions/createTable.js
> +function toStreamLabelString(date) {
Why not take zulu time and remove zulu part?

2016-12-13 12:52 UTC, mariusgrigaitis commented on actions/putItem.js
> +            if (table.LatestStreamArn) {
This code is (almost) duplicated with delete / put actions

2016-12-20 14:26 UTC, kiril-pirozenko-home24 commented
Closing in favour of https://github.com/mhart/dynalite/pull/67

2016-12-20 14:26 UTC, closed without merging